[package]
name = "{{ project_name }}"
version = "0.1.0"
authors = ["{{ git_author }}"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.66"

[profile.release]
lto = true
strip = true
